[tox]
min_version = 4.26
requires = tox>=4.26.0
envlist =
    py310-latest,
    py311-latest,
    py312-latest,
    py313-latest
skip_missing_interpreters = true
skipsdist = false

[testenv]
usedevelop = true
deps =
    pytest
commands =
    pytest \
        src/tests/test_optional_imports.py \
        src/tests/flex_kedro/pipeline/test_pipeline.py \
        src/tests/extras/datasets/mlflow/test_mlflow_dataset.py \
        src/tests/extras/ops/sklearn/test_sklearn_ops.py

[testenv:py310-latest]
basepython = python3.10
deps =
    pytest
    kedro
    kedro-datasets
    mlflow
    scikit-learn
    pandas

[testenv:py311-latest]
basepython = python3.11
deps =
    pytest
    kedro
    kedro-datasets
    mlflow
    scikit-learn
    pandas

[testenv:py312-latest]
basepython = python3.12
deps =
    pytest
    kedro
    kedro-datasets
    mlflow
    scikit-learn
    pandas

[testenv:py313-latest]
basepython = python3.13
deps =
    pytest
    kedro
    kedro-datasets
    mlflow
    scikit-learn
    pandas
